# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\newprj\NewProjectMainWindow_UI.ui'
#
# Created: Tue Dec 13 17:18:32 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NewProjectMainWindow_UI(object):
    def setupUi(self, NewProjectMainWindow_UI):
        NewProjectMainWindow_UI.setObjectName("NewProjectMainWindow_UI")
        NewProjectMainWindow_UI.resize(1020, 667)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/images/app-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewProjectMainWindow_UI.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(NewProjectMainWindow_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.template_cmb = QtGui.QComboBox(self.frame_3)
        self.template_cmb.setObjectName("template_cmb")
        self.horizontalLayout_2.addWidget(self.template_cmb)
        self.template_fold_btn = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.template_fold_btn.sizePolicy().hasHeightForWidth())
        self.template_fold_btn.setSizePolicy(sizePolicy)
        self.template_fold_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/images/gears.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.template_fold_btn.setIcon(icon1)
        self.template_fold_btn.setObjectName("template_fold_btn")
        self.horizontalLayout_2.addWidget(self.template_fold_btn)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.parameters_table = QtGui.QTableWidget(self.frame_2)
        self.parameters_table.setObjectName("parameters_table")
        self.parameters_table.setColumnCount(0)
        self.parameters_table.setRowCount(0)
        self.verticalLayout.addWidget(self.parameters_table)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.proj_folder_input = QtGui.QLineEdit(self.frame)
        self.proj_folder_input.setObjectName("proj_folder_input")
        self.horizontalLayout_4.addWidget(self.proj_folder_input)
        self.proj_input_browse_btn = QtGui.QPushButton(self.frame)
        self.proj_input_browse_btn.setObjectName("proj_input_browse_btn")
        self.horizontalLayout_4.addWidget(self.proj_input_browse_btn)
        self.proj_folder_default_btn = QtGui.QPushButton(self.frame)
        self.proj_folder_default_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/images/default-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.proj_folder_default_btn.setIcon(icon2)
        self.proj_folder_default_btn.setObjectName("proj_folder_default_btn")
        self.horizontalLayout_4.addWidget(self.proj_folder_default_btn)
        self.verticalLayout_2.addWidget(self.frame)
        self.output_file_list = QtGui.QListView(self.frame_2)
        self.output_file_list.setObjectName("output_file_list")
        self.verticalLayout_2.addWidget(self.output_file_list)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.overwrite_all_btn = QtGui.QPushButton(self.frame_4)
        self.overwrite_all_btn.setObjectName("overwrite_all_btn")
        self.horizontalLayout_3.addWidget(self.overwrite_all_btn)
        self.create_all_btn = QtGui.QPushButton(self.frame_4)
        self.create_all_btn.setObjectName("create_all_btn")
        self.horizontalLayout_3.addWidget(self.create_all_btn)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.frame_2)
        NewProjectMainWindow_UI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(NewProjectMainWindow_UI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menubar.setObjectName("menubar")
        NewProjectMainWindow_UI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(NewProjectMainWindow_UI)
        self.statusbar.setObjectName("statusbar")
        NewProjectMainWindow_UI.setStatusBar(self.statusbar)

        self.retranslateUi(NewProjectMainWindow_UI)
        QtCore.QMetaObject.connectSlotsByName(NewProjectMainWindow_UI)

    def retranslateUi(self, NewProjectMainWindow_UI):
        NewProjectMainWindow_UI.setWindowTitle(QtGui.QApplication.translate("NewProjectMainWindow_UI", "New Project Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Select Template", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Project Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.proj_input_browse_btn.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.overwrite_all_btn.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Overwrite All", None, QtGui.QApplication.UnicodeUTF8))
        self.create_all_btn.setText(QtGui.QApplication.translate("NewProjectMainWindow_UI", "Create All New", None, QtGui.QApplication.UnicodeUTF8))

import qt_assets_rc
